spring.application.name=api-gateway

server.port=8093

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=question-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/question-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=quiz-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/quiz-service/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1