spring.application.name=quiz-service

server.port=1091

spring.datasource.url=jdbc:postgresql://localhost:5432/QuizService
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
